branch-defaults:
  github-flow:
    environment: env-dev
global:
  application_name: hello_CICD
  branch: null
  default_ec2_keyname: Alex-custodian
  default_platform: Node.js
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
